// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (clerk_user_id, email, name, currency)
VALUES ($1, $2, $3, $4)
RETURNING id, clerk_user_id, email, name, currency, created_at, updated_at, deleted
`

type CreateUserParams struct {
	ClerkUserID string      `json:"clerkUserId"`
	Email       string      `json:"email"`
	Name        pgtype.Text `json:"name"`
	Currency    pgtype.Text `json:"currency"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClerkUserID,
		arg.Email,
		arg.Name,
		arg.Currency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getCurrentUser = `-- name: GetCurrentUser :one
SELECT id, clerk_user_id, email, name, currency, created_at, updated_at, deleted FROM users
WHERE id = $1 AND deleted = false
LIMIT 1
`

func (q *Queries) GetCurrentUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getCurrentUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_user_id, email, name, currency, created_at, updated_at, deleted FROM users
WHERE clerk_user_id = $1 AND deleted = false
LIMIT 1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, clerk_user_id, email, name, currency, created_at, updated_at, deleted FROM users
WHERE deleted = false
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ClerkUserID,
			&i.Email,
			&i.Name,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = COALESCE($2, email),
    name = COALESCE($3, name),
    currency = COALESCE($4, currency),
    updated_at = NOW()
WHERE id = $1 AND deleted = false
RETURNING id, clerk_user_id, email, name, currency, created_at, updated_at, deleted
`

type UpdateUserParams struct {
	ID       string      `json:"id"`
	Email    pgtype.Text `json:"email"`
	Name     pgtype.Text `json:"name"`
	Currency pgtype.Text `json:"currency"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Currency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}
