// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, icon, color, is_system, default_limit)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, icon, color, is_system, default_limit, created_at, updated_at, deleted
`

type CreateCategoryParams struct {
	UserID       pgtype.UUID    `json:"userId"`
	Name         string         `json:"name"`
	Icon         pgtype.Text    `json:"icon"`
	Color        pgtype.Text    `json:"color"`
	IsSystem     pgtype.Bool    `json:"isSystem"`
	DefaultLimit pgtype.Numeric `json:"defaultLimit"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.IsSystem,
		arg.DefaultLimit,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.IsSystem,
		&i.DefaultLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories
SET deleted = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, name, icon, color, is_system, default_limit, created_at, updated_at, deleted FROM categories
WHERE id = $1 AND deleted = false
LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.IsSystem,
		&i.DefaultLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const getSystemCategories = `-- name: GetSystemCategories :many
SELECT id, user_id, name, icon, color, is_system, default_limit, created_at, updated_at, deleted FROM categories
WHERE is_system = true AND deleted = false
ORDER BY name ASC
`

func (q *Queries) GetSystemCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getSystemCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.IsSystem,
			&i.DefaultLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCategories = `-- name: GetUserCategories :many
SELECT id, user_id, name, icon, color, is_system, default_limit, created_at, updated_at, deleted FROM categories
WHERE user_id = $1 AND deleted = false
ORDER BY created_at ASC
`

func (q *Queries) GetUserCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getUserCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.IsSystem,
			&i.DefaultLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = COALESCE($2, name),
    icon = COALESCE($3, icon),
    color = COALESCE($4, color),
    default_limit = COALESCE($5, default_limit),
    updated_at = NOW()
WHERE id = $1 AND deleted = false
RETURNING id, user_id, name, icon, color, is_system, default_limit, created_at, updated_at, deleted
`

type UpdateCategoryParams struct {
	ID           string         `json:"id"`
	Name         pgtype.Text    `json:"name"`
	Icon         pgtype.Text    `json:"icon"`
	Color        pgtype.Text    `json:"color"`
	DefaultLimit pgtype.Numeric `json:"defaultLimit"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.DefaultLimit,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.IsSystem,
		&i.DefaultLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}
