// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID           string             `json:"id"`
	UserID       pgtype.UUID        `json:"userId"`
	Action       string             `json:"action"`
	ResourceType pgtype.Text        `json:"resourceType"`
	ResourceID   pgtype.UUID        `json:"resourceId"`
	Details      []byte             `json:"details"`
	IpAddress    *netip.Addr        `json:"ipAddress"`
	UserAgent    pgtype.Text        `json:"userAgent"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

type Budget struct {
	ID         string             `json:"id"`
	UserID     pgtype.UUID        `json:"userId"`
	Name       pgtype.Text        `json:"name"`
	Month      pgtype.Date        `json:"month"`
	TotalLimit pgtype.Numeric     `json:"totalLimit"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
	Deleted    pgtype.Bool        `json:"deleted"`
}

type BudgetCategory struct {
	ID          string             `json:"id"`
	BudgetID    pgtype.UUID        `json:"budgetId"`
	CategoryID  pgtype.UUID        `json:"categoryId"`
	LimitAmount pgtype.Numeric     `json:"limitAmount"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Category struct {
	ID           string             `json:"id"`
	UserID       pgtype.UUID        `json:"userId"`
	Name         string             `json:"name"`
	Icon         pgtype.Text        `json:"icon"`
	Color        pgtype.Text        `json:"color"`
	IsSystem     pgtype.Bool        `json:"isSystem"`
	DefaultLimit pgtype.Numeric     `json:"defaultLimit"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	Deleted      pgtype.Bool        `json:"deleted"`
}

type PaymentMethod struct {
	ID             string             `json:"id"`
	UserID         pgtype.UUID        `json:"userId"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	LastFour       pgtype.Text        `json:"lastFour"`
	Brand          pgtype.Text        `json:"brand"`
	IsDefault      pgtype.Bool        `json:"isDefault"`
	IsActive       pgtype.Bool        `json:"isActive"`
	CreditLimit    pgtype.Numeric     `json:"creditLimit"`
	CurrentBalance pgtype.Numeric     `json:"currentBalance"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	Deleted        pgtype.Bool        `json:"deleted"`
}

type Reflection struct {
	ID            string             `json:"id"`
	UserID        pgtype.UUID        `json:"userId"`
	BudgetID      pgtype.UUID        `json:"budgetId"`
	OverallRating pgtype.Int4        `json:"overallRating"`
	IsPrivate     pgtype.Bool        `json:"isPrivate"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	Deleted       pgtype.Bool        `json:"deleted"`
}

type ReflectionQuestion struct {
	ID           string             `json:"id"`
	ReflectionID pgtype.UUID        `json:"reflectionId"`
	Sequence     pgtype.Int4        `json:"sequence"`
	QuestionID   string             `json:"questionId"`
	QuestionText string             `json:"questionText"`
	Answer       pgtype.Text        `json:"answer"`
	Mood         pgtype.Text        `json:"mood"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type ReflectionTemplate struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	IsActive  pgtype.Bool        `json:"isActive"`
	Version   pgtype.Int4        `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type ShareAccess struct {
	ID           string             `json:"id"`
	BudgetID     pgtype.UUID        `json:"budgetId"`
	OwnerID      pgtype.UUID        `json:"ownerId"`
	SharedWithID pgtype.UUID        `json:"sharedWithId"`
	Permission   string             `json:"permission"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

type ShareInvitation struct {
	ID             string             `json:"id"`
	BudgetID       pgtype.UUID        `json:"budgetId"`
	OwnerID        pgtype.UUID        `json:"ownerId"`
	RecipientEmail string             `json:"recipientEmail"`
	Permission     string             `json:"permission"`
	Status         pgtype.Text        `json:"status"`
	ExpiresAt      pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type SyncOperation struct {
	ID            string             `json:"id"`
	UserID        pgtype.UUID        `json:"userId"`
	TableName     string             `json:"tableName"`
	RecordID      string             `json:"recordId"`
	Operation     string             `json:"operation"`
	LocalData     []byte             `json:"localData"`
	ServerData    []byte             `json:"serverData"`
	Status        pgtype.Text        `json:"status"`
	ErrorMessage  pgtype.Text        `json:"errorMessage"`
	AttemptCount  pgtype.Int4        `json:"attemptCount"`
	LastAttemptAt pgtype.Timestamptz `json:"lastAttemptAt"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type TemplateQuestion struct {
	ID              string             `json:"id"`
	TemplateID      pgtype.UUID        `json:"templateId"`
	QuestionID      string             `json:"questionId"`
	QuestionText    string             `json:"questionText"`
	Type            pgtype.Text        `json:"type"`
	IsRequired      pgtype.Bool        `json:"isRequired"`
	HasMoodTracking pgtype.Bool        `json:"hasMoodTracking"`
	SortOrder       pgtype.Int4        `json:"sortOrder"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

type Transaction struct {
	ID                  string             `json:"id"`
	UserID              pgtype.UUID        `json:"userId"`
	BudgetID            pgtype.UUID        `json:"budgetId"`
	CategoryID          pgtype.UUID        `json:"categoryId"`
	PaymentMethodID     pgtype.UUID        `json:"paymentMethodId"`
	Amount              pgtype.Numeric     `json:"amount"`
	Type                pgtype.Text        `json:"type"`
	IsTransfer          pgtype.Bool        `json:"isTransfer"`
	TransferToAccountID pgtype.UUID        `json:"transferToAccountId"`
	Description         pgtype.Text        `json:"description"`
	TransactionDate     pgtype.Date        `json:"transactionDate"`
	IsRecurring         pgtype.Bool        `json:"isRecurring"`
	RecurrencePattern   []byte             `json:"recurrencePattern"`
	CreatedAt           pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `json:"updatedAt"`
	Deleted             pgtype.Bool        `json:"deleted"`
}

type User struct {
	ID          string             `json:"id"`
	ClerkUserID string             `json:"clerkUserId"`
	Email       string             `json:"email"`
	Name        pgtype.Text        `json:"name"`
	Currency    pgtype.Text        `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	Deleted     pgtype.Bool        `json:"deleted"`
}
