// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddBudgetCategory(ctx context.Context, arg AddBudgetCategoryParams) (BudgetCategory, error)
	CheckBudgetAccess(ctx context.Context, arg CheckBudgetAccessParams) (CheckBudgetAccessRow, error)
	CountPendingSyncOperations(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error)
	CreateReflection(ctx context.Context, arg CreateReflectionParams) (Reflection, error)
	CreateReflectionQuestion(ctx context.Context, arg CreateReflectionQuestionParams) (ReflectionQuestion, error)
	CreateReflectionTemplate(ctx context.Context, arg CreateReflectionTemplateParams) (ReflectionTemplate, error)
	CreateShareAccess(ctx context.Context, arg CreateShareAccessParams) (ShareAccess, error)
	CreateShareInvitation(ctx context.Context, arg CreateShareInvitationParams) (ShareInvitation, error)
	CreateSyncOperation(ctx context.Context, arg CreateSyncOperationParams) (SyncOperation, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBudget(ctx context.Context, id string) error
	DeleteCategory(ctx context.Context, id string) error
	DeleteInvitation(ctx context.Context, id string) error
	DeletePaymentMethod(ctx context.Context, id string) error
	DeleteReflection(ctx context.Context, id string) error
	DeleteReflectionTemplate(ctx context.Context, id string) error
	DeleteShareAccess(ctx context.Context, id string) error
	DeleteSyncOperation(ctx context.Context, id string) error
	DeleteSyncedOperations(ctx context.Context, userID pgtype.UUID) error
	DeleteTransaction(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetBudgetByID(ctx context.Context, id string) (Budget, error)
	GetBudgetByMonth(ctx context.Context, arg GetBudgetByMonthParams) (Budget, error)
	GetBudgetCategories(ctx context.Context, budgetID pgtype.UUID) ([]GetBudgetCategoriesRow, error)
	GetBudgetSpent(ctx context.Context, budgetID pgtype.UUID) (interface{}, error)
	// Sync pull queries - fetch records updated since last sync
	GetBudgetsSince(ctx context.Context, arg GetBudgetsSinceParams) ([]Budget, error)
	GetCategoriesSince(ctx context.Context, arg GetCategoriesSinceParams) ([]Category, error)
	GetCategoryByID(ctx context.Context, id string) (Category, error)
	GetCategoryReport(ctx context.Context, arg GetCategoryReportParams) ([]GetCategoryReportRow, error)
	GetCategorySpent(ctx context.Context, arg GetCategorySpentParams) (interface{}, error)
	GetCurrentUser(ctx context.Context, id string) (User, error)
	GetDashboardSummary(ctx context.Context, id string) (GetDashboardSummaryRow, error)
	GetFailedSyncOperations(ctx context.Context, userID pgtype.UUID) ([]SyncOperation, error)
	GetInvitationByID(ctx context.Context, id string) (ShareInvitation, error)
	GetInvitationsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]GetInvitationsByOwnerRow, error)
	GetPaymentMethodByID(ctx context.Context, id string) (PaymentMethod, error)
	GetPendingInvitationsByRecipient(ctx context.Context, recipientEmail string) ([]GetPendingInvitationsByRecipientRow, error)
	GetPendingSyncOperations(ctx context.Context, userID pgtype.UUID) ([]SyncOperation, error)
	GetRecentTransactions(ctx context.Context, arg GetRecentTransactionsParams) ([]GetRecentTransactionsRow, error)
	GetReflectionByBudget(ctx context.Context, budgetID pgtype.UUID) (Reflection, error)
	GetReflectionByID(ctx context.Context, id string) (Reflection, error)
	GetReflectionQuestions(ctx context.Context, reflectionID pgtype.UUID) ([]ReflectionQuestion, error)
	GetShareAccessByBudget(ctx context.Context, budgetID pgtype.UUID) ([]GetShareAccessByBudgetRow, error)
	GetShareAccessByID(ctx context.Context, id string) (ShareAccess, error)
	GetShareAccessForBudgetAndUser(ctx context.Context, arg GetShareAccessForBudgetAndUserParams) (ShareAccess, error)
	GetShareAccessForUser(ctx context.Context, sharedWithID pgtype.UUID) ([]GetShareAccessForUserRow, error)
	GetSpendingByCategory(ctx context.Context, budgetID pgtype.UUID) ([]GetSpendingByCategoryRow, error)
	GetSpendingTrends(ctx context.Context, arg GetSpendingTrendsParams) ([]GetSpendingTrendsRow, error)
	GetSyncOperationByID(ctx context.Context, id string) (SyncOperation, error)
	GetSyncOperationsByUser(ctx context.Context, arg GetSyncOperationsByUserParams) ([]SyncOperation, error)
	GetSystemCategories(ctx context.Context) ([]Category, error)
	GetTemplateByID(ctx context.Context, id string) (ReflectionTemplate, error)
	GetTemplateQuestions(ctx context.Context, templateID pgtype.UUID) ([]TemplateQuestion, error)
	GetTransactionByID(ctx context.Context, id string) (Transaction, error)
	GetTransactionsByBudget(ctx context.Context, budgetID pgtype.UUID) ([]Transaction, error)
	GetTransactionsSince(ctx context.Context, arg GetTransactionsSinceParams) ([]Transaction, error)
	GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error)
	GetUserCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]User, error)
	ListPaymentMethods(ctx context.Context, userID pgtype.UUID) ([]PaymentMethod, error)
	ListReflectionTemplates(ctx context.Context) ([]ReflectionTemplate, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	ListUserBudgets(ctx context.Context, userID pgtype.UUID) ([]Budget, error)
	ListUserReflections(ctx context.Context, userID pgtype.UUID) ([]Reflection, error)
	RemoveBudgetCategory(ctx context.Context, id string) error
	ResolveSyncOperation(ctx context.Context, arg ResolveSyncOperationParams) error
	SetDefaultPaymentMethod(ctx context.Context, userID pgtype.UUID) error
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateBudgetCategory(ctx context.Context, arg UpdateBudgetCategoryParams) (BudgetCategory, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (ShareInvitation, error)
	UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (PaymentMethod, error)
	UpdateReflection(ctx context.Context, arg UpdateReflectionParams) (Reflection, error)
	UpdateReflectionQuestion(ctx context.Context, arg UpdateReflectionQuestionParams) (ReflectionQuestion, error)
	UpdateReflectionTemplate(ctx context.Context, arg UpdateReflectionTemplateParams) (ReflectionTemplate, error)
	UpdateShareAccess(ctx context.Context, arg UpdateShareAccessParams) (ShareAccess, error)
	UpdateSyncOperationStatus(ctx context.Context, arg UpdateSyncOperationStatusParams) (SyncOperation, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
